spring:
  profiles:
    group:
      "local": "local, common"
      "prod" : "prod, common"
    active: local # Select profile
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  config:
    activate:
      on-profile: "common"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DLL_MODE}
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope: account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}
  aud: ${JWT_AUD}
kakao:
  admin-key: ${KAKAO_APP_ADMIN}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: ${SECRET_BASE_PATH}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace  # 파라미터 로그용

thread:
  pool:
    size: 4

firebase:
  key:
    path: "firebase-private-key.json"
    scope: "https://www.googleapis.com/auth/firebase.messaging"

alarm:
  image-url:
    daily-plan-remind: "daily-plan-remind"
    expense-enroll-remind: "expense-enroll-remind"
    goal-end-remind: "goal-end-remind"
